### ISSUE TITLE
Blog about ports, target ports, nodeport, expose(port on container)

### ISSUE THREAD

**Issue by eliteGoblin** [eliteGoblin/my_blog_src#4]
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: tomcat-server
spec:
  type: NodePort
  ports:
  - port: 11111
    targetPort: 80
    nodePort: 32700
  selector:
    app: nginx
```
